name: pre-commit

on:
  push:
    branches:
      - '!main'
      - '!master'
      - 'fixes/**'
      - 'feature/**'
      - 'hotfix/**'
      - 'releases/**'

env:
  TF_VER: "0.14.11"
  TF_DOCS_VER: "v0.16.0"
  TFLINT_VER: "v0.35.0"
  BIN_PATH: "/home/runner/.local/bin"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Install terraform binary
      run: |
        mkdir -p /home/runner/.local/bin
        curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/${TF_DOCS_VER}/terraform-docs-${TF_DOCS_VER}-$(uname)-amd64.tar.gz
        tar -xzf terraform-docs.tar.gz
        chmod +x terraform-docs
        mv terraform-docs ${BIN_PATH}/terraform-docs

    - name: Install TFLint binary
      run: |
        curl -sSLo tflint_linux_amd64.zip https://github.com/terraform-linters/tflint/releases/download/${TFLINT_VER}/tflint_linux_amd64.zip
        unzip tflint_linux_amd64.zip
        chmod +x tflint
        mv tflint ${BIN_PATH}/tflint

    - name: Install Terraform binary
      run: |
        curl -sSLo terraform_${TF_VER}_linux_amd64.zip https://releases.hashicorp.com/terraform/${TF_VER}/terraform_${TF_VER}_linux_amd64.zip
        unzip terraform_${TF_VER}_linux_amd64.zip
        chmod +x terraform
        mv terraform ${BIN_PATH}/terraform

    - name: Enable python
      uses: actions/setup-python@v3

    - name: Install latest pre-commit
      run: pip install --upgrade pre-commit

    - name: Run pre-commit checks
      run: pre-commit run -a
      
    - name: GH commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        # Optional. Commit message for the created commit.
        # Defaults to "Apply automatic changes"
        commit_message: Automated Change
        
        # Optional. Local and remote branch name where commit is going to be pushed
        #  to. Defaults to the current branch.
        #  You might need to set `create_branch: true` if the branch does not exist.
        branch: feature/**
        
        # Optional. Options used by `git-commit`.
        # See https://git-scm.com/docs/git-commit#_options 
        commit_options: '--no-verify --signoff'

        # Optional glob pattern of files which should be added to the commit
        # Defaults to all (.)
        # See the `pathspec`-documentation for git
        # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
        # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
        #file_pattern: . #src/*.js tests/*.js *.php

        # Optional. Local file path to the repository.
        # Defaults to the root of the repository.
        repository: .

        # Optional commit user and author settings
        commit_user_name: My GitHub Actions Bot # defaults to "github-actions[bot]"
        commit_user_email: mukumbu.katja@gmail.com # defaults to "github-actions[bot]@users.noreply.github.com"
        commit_author: Patrick <actions@github.com> # defaults to author of the commit that triggered the run

        # Optional. Tag name being created in the local repository and 
        # pushed to remote repository and defined branch.
        tagging_message: 'beta1.0.0'

        # Optional. Option used by `git-status` to determine if the repository is 
        # dirty. See https://git-scm.com/docs/git-status#_options
        status_options: '--untracked-files=no'

        # Optional. Options used by `git-add`.
        # See https://git-scm.com/docs/git-add#_options
        add_options: '-u'

        # Optional. Options used by `git-push`.
        # See https://git-scm.com/docs/git-push#_options
        push_options: '--force'
        
        # Optional. Disable dirty check and always try to create a commit and push
        skip_dirty_check: true        
        
        # Optional. Skip internal call to `git fetch`
        skip_fetch: true        
        
        # Optional. Skip internal call to `git checkout`
        skip_checkout: true

        # Optional. Prevents the shell from expanding filenames. 
        # Details: https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html
        disable_globbing: true

        # Optional. Create given branch name in local and remote repository.
        create_branch: true
